---
- name: 'Install gitlab-ce'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.install_one_or_more_packages'
      packages_to_be_installed:
        # required to have chef not fail with
        # 'Chef::Exceptions::CannotDetermineNodeName: Unable to determine node
        # name'
        - hostname
        # required to have chef not fail with
        # execute[load sysctl conf kernel.shmall] (postgresql::sysctl line 56)
        # had an error: Errno::ENOENT: No such file or directory - sysctl
        - procps
        - gitlab-ce
